### ISSUE TITLE
Misinforming project description

### ISSUE THREAD

**Issue by milosdjakonovic** [bendc/animateplus#11]
"Animate Plus is a CSS and SVG animation library for modern browsers."

While this technically **is true**, this description is misinforming in term of animation mechanism - I was surprised when I found out that animateplus use neither css transitions nor css keyframe animations.

Maybe: "Animate Plus is a HTML5 and SVG Javascript-powered animation library for modern browsers." or something similar.

**Comment by bendc** [comment]
Yeah I hesitated when I was writing it but, while not perfect, I think it's fine. Thanks for pointing it out though!

**Comment by kirkins** [comment]
hmm I thought this was css based too. I was always told that css based animation is faster than JS.

Use to use https://github.com/blackberry/Alice a long time ago and thought this might be something similar.
