### ISSUE TITLE
Add support for spring effect

### ISSUE THREAD

**Issue by samosale** [bendc/animateplus#17]
It would be nice to have ios- like spring easing. tnx!

**Comment by bendc** [comment]
What do you mean? The default easing has an iOS-like spring curve ([example](http://sharedfil.es/fyLrz24QiC.html)).

**Comment by samosale** [comment]
I mean like spring effect with full options like this : http://dynamicsjs.com/

**Comment by bendc** [comment]
The goal was to keep the spring configuration simple, so you can tweak the elasticity just by passing a single number ([example](http://sharedfil.es/UkgtwWVk2t.html)). If you need more granular settings, I recommend you to use Dynamics :)
