### ISSUE TITLE
IE8,IE9 support

### ISSUE THREAD

**Issue by Gugi25** [bendc/animateplus#18]
Hi, this is a perfect library for creating HTML5 hand-coded banners without using any software (GWD, Adobe Animate). Output is perfect small (lot of ad servers have limits up to 50kB for an HTML5 banner) and does all the animations needed in banners.

Do you plan IE8 and IE9 support ?

How can we easily achieve it when no support is planned, please ?

**Comment by bendc** [comment]
Hi! As the description says, Animate Plus is for _modern browsers_ so I don't plan on supporting IE8 and 9. While not trivial, it wouldn't be impossible for you to fork it and to make it compatible though.
