### ISSUE TITLE
complete callback called before the animation is over

### ISSUE THREAD

**Issue by mbaudry** [bendc/animateplus#20]
Hello, 

I have an issue when a try to execute a method in the  `complete` callback (on Chrome). It seems the callback is called before the animation is over. Here is an example:  https://jsfiddle.net/tvh7qc37/7/. If you open the console, you will see that the code is stopped by the debugger before the animation is over.

thank you for your help !

**Comment by bendc** [comment]
I'm not entirely sure how `debugger` works as I never rely on it, but I'm pretty sure the `complete` callback is always called _after_ the animation. You can try replacing your `debugger` statement with something like `console.log(document.querySelector(".foreground").style.transform)` and you'll always get `scale(0)`.
