### ISSUE TITLE
Clarify browser support

### ISSUE THREAD

**Issue by fvsch** [bendc/animateplus#21]
Hi,

Wondering if it would be possible to clarify the current browser support in the README? E.g. adding a "Browser Support" section at the end.

Cool project btw, thanks for sharing!

**Comment by fvsch** [comment]
Did a quick test of the demos:

- Edge works fine, with one alignment bug on http://animateplus.com/demos/download-button/ (arrow shape is aligned to the top left, instead of center top).
- IE11 doesn't work, not sure if it's because of lack of essential features or because of fixable JS bugs.

**Comment by bendc** [comment]
Yeah I dropped IE11 support with release 1.4. Agreed I should document browser support as I tend to be fairly aggressive in that regard :p

**Comment by iamvdo** [comment]
@bendc You can be aggresive, but you should have followed Semver and released it as 2.0.

**Comment by bendc** [comment]
I guess you're right. I thought a _minor_ release would be appropriate since I haven't introduced API changes but, yeah, should likely have been labeled as _major_.

**Comment by jhabdas** [comment]
@bendc Here's a simple rig to model after if you want to package up this library before someone else does: https://github.com/jhabdas/fetch-inject. Thanks for the pithy API.

**Comment by bendc** [comment]
Fixed in v2.0.0
