### ISSUE TITLE
Selecting pseudo elements (before/after)

### ISSUE THREAD

**Issue by uzumakinaruto123** [bendc/animateplus#22]
Can pseudo elements be selected ? I am planning to animate bacground image.I have something like this

```
.container:before {
    background-image: url("xyz.png");
}
```

How can i select `.container:before` ?

Thanks !

**Comment by samosale** [comment]
@uzumakinaruto123 try https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

var container      = document.querySelector('.container'), 
      result   = getComputedStyle(container, ':before').backgroundImage;


But, not sure if animate.js supports that...

**Comment by uzumakinaruto123** [comment]
Thanks alot @samosale  will try that. But , Mobile browser support is still unknown as per that link. That would be the deal breaker if it doesn't. I will try first :)  Thanks again
