### ISSUE TITLE
glitch in webkit browsers on mobile devices

### ISSUE THREAD

**Issue by jigganstiso** [bendc/animateplus#23]
I've noticed that before animation starts (fadeInUp-example) element is visible for less than a 1 sec then animation starts, i'ts really annoying because it ruins the effect. I've tried many things but nothing seems to work, any ideas how to fix this? THIS IS HAPPENING ONLY ON MOBILE DEVICES

**Comment by bendc** [comment]
I don't know what this "fadeInUp-example" refers to. Closing for now as I don't have any code example to look at.
