### ISSUE TITLE
Animating percentages from/to px

### ISSUE THREAD

**Issue by iamvdo** [bendc/animateplus#26]
Seems to be a bug at first:

```js
animate({
  el: 'div',
  translateX: ['100%', 0]
})
```
or
```js
animate({
  el: 'div',
  translateX: '100%',
  direction: 'reverse'
})
```

I expect an animation from `100%` to `0`, but got from `100px` to `0`. See: http://jsbin.com/fitezotivo/edit?js,output

It seems to occur when animating percentages from/to px (as no unit is converted to px). Using `translateX: ['100%', '0%']` fix the first case, but we're still facing the issue when using `direction: reverse`

**Comment by bendc** [comment]
Fixed in v2.0.0
