### ISSUE TITLE
Div gets blured after animation

### ISSUE THREAD

**Issue by samosale** [bendc/animateplus#27]
After runing 
`animate({
  el: 'article',
  translateY: ['100%', '0%'],
  scale: [0,1]
})`
my div gets blured completely
![screenshot from 2017-06-17 09-09-01](https://user-images.githubusercontent.com/13149550/27250976-aca59c48-533c-11e7-8b6b-5606e00b7950.png)

**Comment by bendc** [comment]
Fixed in v2.0.0
