### ISSUE TITLE
fyI: is not working 

### ISSUE THREAD

**Issue by Noe007** [bendc/animateplus#32]
Hi, I just went thought all the examples and none of them seen to work....

![image](https://user-images.githubusercontent.com/12816840/33330057-d7001cdc-d42b-11e7-8e77-2e9e0c712a8c.png)

**Comment by bendc** [comment]
Check the "Browser support" section. Thanks!

**Comment by Noe007** [comment]
I just did, I was about to close this issue, but i guess you're faster than me... Thanks
