### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by davidmerrique** [bendc/animateplus#34]
Hi. These are some smooth animations.

I just discovered a bug. 

If you load a page in the background (You can try it on any of the examples by going to a different tab and reloading the animation tab), an error is thrown because a property isn't set. 

Checking for the existence of `paused.all` before calling `all.forEach` fixes it.

https://github.com/bendc/animateplus/blob/c2eff0ff45663b4c91a78aec0b176b52f8755f5d/animateplus.js#L316

Thanks!

**Comment by bendc** [comment]
Good catch, will fix. Thanks!

**Comment by bendc** [comment]
Fixed -- sorry for the delay!
