### ISSUE TITLE
Cannot call function as a class

### ISSUE THREAD

**Issue by aulneau** [bendc/animateplus#38]
Hi there!

I'm very excited to try this out, but I've been trying to import the library in my react project and I cannot get it working unfortunately. 

I keep getting the error `TypeError: Cannot call a class as a function`.

I'm importing as : `import animate from 'lib/animateplus'`

Any help would be much appreciated!

Best

**Comment by AustinPaquette** [comment]
Try

```javascript
import animate from "~lib/animateplus";
```

though looking in `package.json` I'm inclined to suggest one of the following two options

```javascript
import animate from "~animateplus";
import animate from "animateplus";
```

I don't work with react specifically but I'm sure we can get it working. Update me if none of these options work!

**Comment by aulneau** [comment]
Thanks for your reply! I don't believe the import is not the issue (I have aliases / a module resolver babel plugin) , I _think_ the issue is coming from the way its exported and then the way Im using the export as a function.

**Comment by bendc** [comment]
Hi! Closing the issue as this is related to your tooling/setup, not to this library specifically.
