### ISSUE TITLE
Example Repo

### ISSUE THREAD

**Issue by oyeanuj** [bendc/animateplus#40]
Hi @bendc, thank you for creating this library! Your examples were super inspiring, and I was wondering if there was a way to look at the code to help understand how the library works?

**Comment by bendc** [comment]
Hi! You can have a look at the library's [code](https://github.com/bendc/animateplus/blob/master/animateplus.js) or any of the examples by simply inspecting the code ([example](http://animateplus.com/examples/timeline/index.js)).

**Comment by vesper8** [comment]
why not simply include the examples on github

and it would be cool if it had its own repo because then people could do PRs to add other cool and possibly more complex examples

**Comment by Paquette** [comment]
@vesper8 what's preventing you from making a PR to the readme on this repo? I don't know if there's any benefit to a separate repo. Generally best to keep that all together.
