### ISSUE TITLE
Animations do not work on mobile safari

### ISSUE THREAD

**Issue by p5kb5n** [bendc/animateplus#41]
I wasn't able to get animations working on iOS in mobile safari.

This example  fails with the the following error message for me:
http://animateplus.com/examples/stress-test/
```
[Error] SyntaxError: Unexpected token '...'. Expected a property name.
	promiseReactionJob
```

**Comment by bendc** [comment]
You need iOS 11.3 to be able to use the library (and view the examples) without transpiling it.
