### ISSUE TITLE
is this also suited for 3d transform animations?

### ISSUE THREAD

**Issue by vesper8** [bendc/animateplus#43]
I noticed that all of your animation examples are 2d and there isn't any tilt or flip or anything that looks like 3d. I really the simplicity of your syntax but am wondering if this is also suited for mixing 3d and 2d animations together?

**Comment by bendc** [comment]
Absolutely! Animate Plus can animate anything CSS can do. Here's a quick [3D animation example](http://sharedfil.es/hUo3axp744.html). Let me know if you need anything else!
