### ISSUE TITLE
Translate3d Support

### ISSUE THREAD

**Issue by spacehunter** [bendc/animateplus#45]
Hi there!

Is translate3d not support?  If not, would be a nice addition.

**Comment by spacehunter** [comment]
Typed too soon, it is supported!

ex.  animate({
          elements: "p",
          delay: 1500,
          easing: "out-cubic",
          opacity: [1, 0],
          transform: ["perspective(1000px) translate3d(0px,0px,0px)", "perspective(1000px) translate3d(0px,0px,1000px"]
 }).

**Comment by pqt** [comment]
@spacehunter https://github.com/bendc/animateplus/issues/43

**Comment by bendc** [comment]
Thanks @AustinPaquette :)
