### ISSUE TITLE
Getting started example not working properly on chrome

### ISSUE THREAD

**Issue by aecorredor** [bendc/animateplus#46]
The example at http://animateplus.com/examples/getting-started/ is not working properly on chrome. It's working fine on safari mobile and on firefox desktop.

The animation on chrome scales the first box, but the last two don't animate the entrance, they just appear after the delay out of nowhere. Then the translate animation does work properly.

**Comment by bendc** [comment]
I _think_ that was a weird bug introduced in Chrome 67 (the style values are applied correctly, so it's presumably a rendering issue). Would you mind try updating to Chrome 68?

**Comment by aecorredor** [comment]
@bendc for sure. Let me update it and I’ll let you know. Thanks!

**Comment by aecorredor** [comment]
@bendc working perfectly on chrome 68. Closing this. Thanks for pointing out the issue.
