### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by Omnipresent** [bendc/animateplus#47]
I am trying to use this in a simple static HTML website. I've imported the raw animateplus.js, however, in chrome it is showing me a JS error "Unexpected token export". What is the best way to resolve this?

**Comment by bendc** [comment]
You have to import Animate Plus as a module, e.g. :
```javascript
<script type="module">
  import animate from "https://cdn.jsdelivr.net/npm/animateplus@2/animateplus.js";
  // animate({...});
</script>
```
Refer to the code of one of the [examples](http://animateplus.com/examples/getting-started/) if you need a starter template.
