### ISSUE TITLE
Issue with IE/Edge

### ISSUE THREAD

**Issue by murilobd** [bendc/animateplus#48]
I am using this library with vue-cli and got a problem running on IE/Edge. To fix that, I had to transpile with Babel and import the transpilled version instead of the package version.
Basically, what I've done was that:
```
babel transform-object-rest-spread node_modules/animateplus/animateplus.js --out-file animate.js
```
and on import part:
```
import animate from "./animate.js"
```

**Comment by bendc** [comment]
Sorry, what's the question?

**Comment by murilobd** [comment]
Just a note so if someone runs with the same issue I had!
I took some time to realize that webpack (vue-cli) wasn't processing correctly the library and because of that, IE/Edge was reporting an error!

**Comment by bendc** [comment]
Ah yeah, thanks for letting me know!
