### ISSUE TITLE
Comparison with other modules?

### ISSUE THREAD

**Issue by yellow1912** [bendc/animateplus#49]
How would this work in comparison with Greensock or Animejs? I'm considering this one and Animejs (which is slightly bigger) for use in various projects.

**Comment by bendc** [comment]
I'd say the three of them are solid choices, so it really depends on what you prioritize. GreenSock is the most powerful one but also the heaviest. Animate Plus is the most straightforward and the lightest. Anime is somewhere in the middle.

Happy animating!
