### ISSUE TITLE
Cannot call JS method at the end of animation

### ISSUE THREAD

**Issue by dumplingbao** [bendc/animateplus#52]
I want to call the JS method after the animation is finished. It seems that this operation is not supported now, only simple operation can be performed.
Can you answer it? Thank you.

**Comment by dumplingbao** [comment]
Writing format
resolved

**Comment by bendc** [comment]
You can call any function after the promise resolves.

**Comment by dumplingbao** [comment]
After trying again, it has been solved. Thank you!
