### ISSUE TITLE
Best practice/function to make animated sequence

### ISSUE THREAD

**Issue by eramdam** [bendc/animateplus#6]
This lib is awesome but I'm struggling to do animated sequence without ending up with a nested callbacks hell. Any best practice for this, or even better, a `runSequence`-like method?

**Comment by bendc** [comment]
Thanks! There are a few different options and the appropriate implementation will depend on the result you're looking for, but here's [one possible way to do it](http://sharedfil.es/dxLKpNEkII.html).

**Comment by eramdam** [comment]
@bendc Thanks! Maybe would be useful to add this simple exemple in the README ? :)
