### ISSUE TITLE
Map in animate.min.js

### ISSUE THREAD

**Issue by forresto** [bendc/animateplus#7]
How do you compile animate.min.js? It looks like it is compiling some ES6 stuff like `const`, but not `Map`, which is causing some sad browsers to be sad.

**Comment by bendc** [comment]
Hello! Which browsers are causing you `Map` issues?

**Comment by forresto** [comment]
Android 4.something...

**Comment by bendc** [comment]
Hm yeah, Animate Plus focuses on modern browsers (read IE10+ and alike). I'd suggest aggressively dropping dying browsers but if you really want to compile it yourself, you can just use Babel and modify its `_slicedToArray` and `_toConsumableArray` functions like [this](http://sharedfil.es/JUOJJNFNNw.txt) (`_slicedToArray` is basically useless).
