### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by YouriT** [bendc/animateplus#8]
Hi Benjamin,

Would it be possible to push animateplus to the Bower package manager on top of your NPM one?
Great plugin by the way!

Cheers,

Youri

**Comment by andrewBalekha** [comment]
Created a pull request 
https://github.com/bendc/animateplus/pull/9

**Comment by YouriT** [comment]
:+1:

**Comment by williambout** [comment]
:+1:

**Comment by bendc** [comment]
[Closing for now](https://github.com/bendc/animateplus/pull/9#issuecomment-160968098), but keeping an eye on it ;)
